name: Actions WorkFlow
on: 
  push:
    branches:
      - master
      - 'feature/*' #mathches feature/blah, feature/blahh but  not feature/blah/blah
      - 'feature/**' #matches feature/blah/blah
      - '!feature/feah' #to exclude matching feah branch
    # tags:
    #   - ""
    # paths:
    #   - '**.js' this means when push contains .js files this workflow will run
    # branches-ignore:
    #   - develope  branches and branches all wont work together, 
  # schedule:
  #   - cron: "0/5 * * * *"
  # repository_dispatch:
  #   types: [build]
  # pull_request:
  #   types: [closed, assigned, opened, reopened]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{github.event.client_payload.env}}
      - name: checkout
        uses: actions/checkout@v3
      - name: List files
        run:  |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
      - name: simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Shalu
      - name: Log greeting time
        run:  echo "${{steps.greet.outputs.time}}"
